### ISSUE TITLE
ActivityComponentBuilderHost question

### ISSUE THREAD

**Issue by jemshit** [trevjonez/Dagger2-MultiBinding-Android-Example#3]
Hi, why don't we do this
```java
<ComponentBuilderType extends ActivityComponentBuilder> ComponentBuilderType
    getComponentBuilder(Class<? extends Activity> key, Class<? extends ComponentBuilderType> builderType);
```

instead of this:
```java
<ActivityType extends Activity, ComponentBuilderType extends ActivityComponentBuilder> ComponentBuilderType 
getComponentBuilder(Class<? extends ActivityType> key, Class<? extends ComponentBuilderType> builderType);
}
```
in **ActivityComponentBuilderHost** ?

**Comment by trevjonez** [comment]
Looks like an oversight on my part. I'll make some adjustments. I may go create a separate library project with a bunch of the interfaces here then rework this sample project to use it.

**Comment by trevjonez** [comment]
Looking at it closer we could use the extra generic param to provide compiler errors if you were to mismatch the activity type and component builder type. It would be some serious generic madness but protect you from copy paste mistakes.
```java
<A extends Activity, B extends ActivityComponentBuilder<A, ?>> B getActivityComponentBuilder(Class<A> activityKey, Class<B> builderType);
```

Not so bad if we drop down to single cap naming of the generic params.

**Comment by trevjonez** [comment]
I updated this project and readme a tiny bit. It now uses https://github.com/trevjonez/Inject-Android for all the base interface types.

Like i suspected, by more fully defining the relation between generic params on this method it provides a bit of mismatch safety from the compiler.

Keep in mind all of this really comes down to how you like to write your code. I have a tendency to love generics too much and this may be a manifestation of that :)

**Comment by jemshit** [comment]
> I have a tendency to love generics too much and this may be a manifestation of that :)

I noticed :D Thanks for the answer, Inject-Android looks neat
